[build]
  command = "npm i && npm audit fix && cd api && npm i && npm audit fix && cd ../web-react && npm i && npm audit fix && cd .. && npm run build && cp api/build/graphql-schema.js api/build/functions/graphql/. && cp api/build/schema.graphql api/build/functions/graphql/.  && cd api/src/functions/graphql && npm i && npm audit fix"
  publish = "web-react/build"
  functions = "api/build/functions"

[dev]
  command = "npm start"
  port=8000 # destination port to use in browser. Lambda dev server is started on same port
  targetPort=3000 # port that local rollup server is running on
  framework= "#custom"


  NEO4J_URI = "Neo4j URI (ex: bolt://localhost:7687)"
  NEO4J_USER = "Neo4j User"
  NEO4J_PASSWORD = "Neo4j Password"
  
  
[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200